{
    "name": "POS Planning",
    "version": "1.1.5",
    "category": "Point of Sale",
    "summary": "Full Suite: POS Planning, Website Booking, Portal, and Backend Availability Management",
    "author": "Talal Agile ",
    "depends": [
        "point_of_sale",
        "planning",
        "website",
        "product",
        "sale",
        "portal",
        "pos_sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/planning_slot_views.xml",
        "views/planning_availability_views.xml",
        "views/product_views.xml",
        "views/sale_order_views.xml",
        "views/website_templates.xml",
        "views/homepage_layout.xml",
        "views/planning_slot_actions.xml",
        "views/hr_employee_views.xml",
        "views/my_bookings_templates.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "web_gantt/static/src/**/*",
            "pos_planning/static/src/app/gantt_overrides/pos_planning_mock_modules.js",
            "pos_planning/static/src/app/gantt_overrides/pos_planning_mock_templates.xml",
            "planning/static/src/components/**/*",
            "planning/static/src/views/**/*",
            "planning/static/src/scss/planning_gantt.scss",
            "pos_planning/static/src/app/services/pos_store.js",
            "pos_planning/static/src/app/components/navbar/navbar.js",
            "pos_planning/static/src/app/components/navbar/navbar.xml",
            "pos_planning/static/src/app/components/booking_notification/booking_notification.js",
            "pos_planning/static/src/app/components/booking_notification/booking_notification.xml",
            "pos_planning/static/src/app/components/sale_order_button/sale_order_button.js",
            "pos_planning/static/src/app/components/sale_order_button/sale_order_button.xml",
            "pos_planning/static/src/app/screens/product_screen/product_screen.xml",
            (
                "remove",
                "planning/static/src/components/avatar_card_employee/avatar_card_employee_patch.js",
            ),
            ("remove", "web_gantt/static/src/**/*.dark.scss"),
            ("remove", "planning/static/src/views/planning_graph/**"),
            ("remove", "planning/static/src/views/planning_pivot/**"),
            ("remove", "planning/static/src/views/planning_slot_analysis_graph/**"),
            ("remove", "planning/static/src/views/planning_slot_analysis_pivot/**"),
            ("remove", "planning/static/src/views/planning_contract_gantt/**"),
        ],
        "web.assets_frontend": [
            "pos_planning/static/src/scss/website_booking.scss",
            "pos_planning/static/src/js/website_booking.js",
        ],
    },


    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
